version: '3.8'

services:
  nodeapp:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo


  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

volumes:
  mongo-data:
